initial work on OSX compatibility

diff --git a/pype b/pype
--- a/pype
+++ b/pype
@@ -31,7 +31,11 @@ pushd $DIR > /dev/null
 # Set python interpreter name
 PYTHON="python3"
 # Set path to environment if not set
-export PYPE_ENV=${PYPE_ENV:="/opt/pype/pype_env2"}
+if [[ "$OSTYPE" =~ ^darwin.* ]]; then
+  export PYPE_ENV=${PYPE_ENV:="~/Library/pype/pype_env2"}
+else
+  export PYPE_ENV=${PYPE_ENV:="/opt/pype/pype_env2"}
+fi
 # Set debug level if not set
 export PYPE_DEBUG=${PYPE_DEBUG:=0}
 # Process passed arguments
@@ -122,6 +126,48 @@ export PATH="$PYPE_ROOT/vendor/bin/ffmpeg_exec/linux/bin:$PATH"
 if [[ -z $PYPE_LOG_NO_COLORS ]]; then
   source "$PYPE_ROOT/pypeapp/colors.sh"
 fi
+
+have_command_line_tools() {
+  [[ -e "/Library/Developer/CommandLineTools/usr/bin/git" ]]
+}
+
+have_sudo_access() {
+  if [[ -z "${HAVE_SUDO_ACCESS-}" ]]; then
+    /usr/bin/sudo -l mkdir &>/dev/null
+    HAVE_SUDO_ACCESS="$?"
+  fi
+
+  if [[ "$HAVE_SUDO_ACCESS" -ne 0 ]]; then
+    echo -e "${BIRed}!!!${RST} Need sudo access on MacOS"
+    return 1
+  fi
+
+  return "$HAVE_SUDO_ACCESS"
+}
+
+execute() {
+  if ! "$@"; then
+    echo -e "${BIRed}!!!${RST} Failed execution of ${BIWhite}[ $@ ]${RST}"
+  fi
+}
+
+###############################################################################
+# Execute command using sudo
+# This is used on MacOS to handle Xcode command line tools installation
+###############################################################################
+execute_sudo() {
+  local -a args=("$@")
+  if [[ -n "${SUDO_ASKPASS-}" ]]; then
+    args=("-A" "${args[@]}")
+  fi
+  if have_sudo_access; then
+    echo -e "${BIGreen}>->${RST} sudo: [${BIWhite} ${args[@]} ${RST}]"
+    execute "/usr/bin/sudo" "${args[@]}"
+  else
+    echo -e "${BIGreen}>->${RST} [${BIWhite} ${args[@]} ${RST}]"
+    execute "${args[@]}"
+  fi
+}
 
 ###############################################################################
 # Display spinner for running job. Job must be running in a background.
@@ -459,7 +505,11 @@ detect_git () {
 ###############################################################################
 test_offline () {
   echo -e "${BIGreen}>>>${RST} Testing if we are online ... \c"
-  ping -q -w1 -c1 8.8.8.8 &> /dev/null || { echo -e "${BIYellow}OFFLINE${RST}"; f_offline=1; return 1; }
+  local wait="-w1"
+  if [[ "$OSTYPE" =~ ^darwin.* ]]; then
+    local wait="-W1"
+  fi
+  ping -q ${wait} -c1 8.8.8.8 &> /dev/null || { echo -e "${BIYellow}OFFLINE${RST}"; f_offline=1; return 1; }
   echo -e "${BIGreen}ONLINE${RST}"
 }
 
@@ -578,6 +628,60 @@ main () {
         echo -e "${BIYellow}NOT FOUND${RST}"
       fi
       test_offline
+
+      if [[ $OSTYPE =~ ^darwin.* ]]; then
+        if ! have_command_line_tools; then
+          echo -e "${BIYellow}>>>${RST} We need to install ${IWhite}Xcode Command Line Tools${RST}"
+          if [ "$_offline" == 1 ] ; then
+            echo -e "${BIRed}!!!${RST} but you are offline, so we cannot download it. Install it manually or go online and try again"
+            return 1
+          fi
+          echo -e "${IGreen}>>>${RST}Searching online for the Command Line Tools"
+          # This is taken and modified from Homebrew installation script.
+          # All credits should go there.
+          # It seems that we need Xcode command line tools to install dependencies
+          # via pip on MacOS, like Pillow, etc. Also we need to use them to set
+          # few things on newer systems (like 10.14 and 10.15) to point to corrent
+          # location of various header files (zlib, ...)
+          #
+          # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
+          clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
+          execute_sudo "/usr/bin/touch" "$clt_placeholder"
+
+          clt_label_command="/usr/sbin/softwareupdate -l |
+                              grep -B 1 -E 'Command Line Tools' |
+                              awk -F'*' '/^ *\\*/ {print \$2}' |
+                              sed -e 's/^ *Label: //' -e 's/^ *//' |
+                              sort -V |
+                              tail -n1"
+          clt_label="$(chomp "$(/bin/bash -c "$clt_label_command")")"
+
+          if [[ -n "$clt_label" ]]; then
+            echo -e "Installing $clt_label"
+            execute_sudo "/usr/sbin/softwareupdate" "-i" "$clt_label"
+            execute_sudo "/bin/rm" "-f" "$clt_placeholder"
+            execute_sudo "/usr/bin/xcode-select" "--switch" "/Library/Developer/CommandLineTools"
+          fi
+        fi
+        # Headless install may have failed, so fallback to original 'xcode-select' method
+        if should_install_command_line_tools && test -t 0; then
+          echo -e "Installing the Command Line Tools (expect a GUI popup):"
+          execute_sudo "/usr/bin/xcode-select" "--install"
+          echo "Press any key when the installation has completed."
+          getc
+          execute_sudo "/usr/bin/xcode-select" "--switch" "/Library/Developer/CommandLineTools"
+        fi
+
+        if [[ -z "${HOMEBREW_ON_LINUX-}" ]] && ! output="$(/usr/bin/xcrun clang 2>&1)" && [[ "$output" == *"license"* ]]; then
+          abort "$(cat <<EOABORT
+You have not agreed to the Xcode license.
+Before running the installer again please agree to the license by opening
+Xcode.app or running:
+sudo xcodebuild -license
+EOABORT
+)"
+        fi
+      fi
 
       # install environment
       install_environment || return 1
